enum Territory {
  Switzerland,
  Adriatic_Sea,
	Aegean_Sea,
	Albania,
	Ankara,	scAnkara,
	Apulia,
	Armenia,
	Baltic_Sea,
	Barents_Sea,
	Belgium,	scBelgium,
	Berlin,	scBerlin,
	Black_Sea,
	Bohemia,
	Brest,	scBrest,
	Budapest,	scBudapest,
	Bulgaria,	scBulgaria,
	Bulgaria__ec,
	Bulgaria__sc,
	Burgundy,
	Clyde,
	Constantinople,	scConstantinople,
	Denmark,	scDenmark,
	Eastern_Mediterranean,
	Edinburgh,	scEdinburgh,
	English_Channel,
	Finland,
	Galicia,
	Gascony,
	Greece,	scGreece,
	Gulf_of_Lyon,
	Gulf_of_Bothnia,
	Helgoland_Bight,
	Holland,	scHolland,
	Ionian_Sea,
	Irish_Sea,
	Kiel,	scKiel,
	Liverpool,	scLiverpool,
	Livonia,
	London,	scLondon,
	Marseilles,	scMarseilles,
	Mid_Atlantic_Ocean,
	Moscow,	scMoscow,
	Munich,	scMunich,
	Naples,	scNaples,
	North_Atlantic_Ocean,
	North_Africa,
	North_Sea,
	Norway,	scNorway,
	Norwegian_Sea,
	Paris,	scParis,
	Picardy,
	Piedmont,
	Portugal,	scPortugal,
	Prussia,
	Rome,	scRome,
	Ruhr,
	Rumania,	scRumania,
	Serbia,	scSerbia,
	Sevastopol,	scSevastopol,
	Silesia,
	Skagerrak,
	Smyrna,	scSmyrna,
	Spain,	scSpain,
	Spain__nc,
	Spain__sc,
	St_Petersburg,	scSt_Petersburg,
	St_Petersburg__nc,
	St_Petersburg__sc,
	Sweden,	scSweden,
	Syria,
	Trieste,	scTrieste,
	Tunis,	scTunis,
	Tuscany,
	Tyrolia,
	Tyrrhenian_Sea,
	Ukraine,
	Venice,	scVenice,
	Vienna,	scVienna,
	Wales,
	Warsaw,	scWarsaw,
	Western_Mediterranean,
	Yorkshire,
}
export default Territory
