import ProvinceId from '@shared/types/enums/ProvinceId';

 const getLocationFromId = (locationId: ProvinceId): string => {
  const tileName = tileNames[locationId]
  if (!tileName) console.trace(`NO TILE FOUND WITH ID ${locationId}`)
  return tileName
}

export default getLocationFromId


// ! If editing this object, make sure to edit the one in getIdFromLocation as well!
const tileNames: {[key in ProvinceId]: string} = {
  'nat': 'North_Atlantic_Ocean',
  'nrg': 'Norwegian_Sea',
  'bar': 'Barents_Sea',
  'stp/nc': 'St_Petersburg__nc',
  'stp': 'St_Petersburg',
  'mos': 'Moscow',
  'sev': 'Sevastopol',
  'arm': 'Armenia',
  'syr': 'Syria',
  'eas': 'Eastern_Mediterranean',
  'ion': 'Ionian_Sea',
  'tun': 'Tunis',
  'naf': 'North_Africa',
  'mid': 'Mid_Atlantic_Ocean',
  'iri': 'Irish_Sea',
  'lvp': 'Liverpool',
  'cly': 'Clyde',
  'edi': 'Edinburgh',
  'nth': 'North_Sea',
  'nwy': 'Norway',
  'stp/sc': 'St_Petersburg__sc',
  'lvn': 'Livonia',
  'war': 'Warsaw',
  'ukr': 'Ukraine',
  'bla': 'Black_Sea',
  'ank': 'Ankara',
  'smy': 'Smyrna',
  'aeg': 'Aegean_Sea',
  'gre': 'Greece',
  'nap': 'Naples',
  'tys': 'Tyrrhenian_Sea',
  'wes': 'Western_Mediterranean',
  'spa/sc': 'Spain__sc',
  'spa': 'Spain',
  'spa/nc': 'Spain__nc',
  'por': 'Portugal',
  'gas': 'Gascony',
  'bre': 'Brest',
  'eng': 'English_Channel',
  'wal': 'Wales',
  'yor': 'Yorkshire',
  'ska': 'Skagerrak',
  'swe': 'Sweden',
  'fin': 'Finland',
  'bot': 'Gulf_of_Bothnia',
  'bal': 'Baltic_Sea',
  'pru': 'Prussia',
  'sil': 'Silesia',
  'gal': 'Galicia',
  'rum': 'Rumania',
  'bul/ec': 'Bulgaria__ec',
  'bul': 'Bulgaria',
  'con': 'Constantinople',
  'bul/sc': 'Bulgaria__sc',
  'ser': 'Serbia',
  'alb': 'Albania',
  'adr': 'Adriatic_Sea',
  'apu': 'Apulia',
  'rom': 'Rome',
  'tus': 'Tuscany',
  'gol': 'Gulf_of_Lyon',
  'mar': 'Marseilles',
  'bur': 'Burgundy',
  'par': 'Paris',
  'pic': 'Picardy',
  'lon': 'London',
  'bel': 'Belgium',
  'hol': 'Holland',
  'hel': 'Helgoland_Bight',
  'den': 'Denmark',
  'ber': 'Berlin',
  'mun': 'Munich',
  'boh': 'Bohemia',
  'vie': 'Vienna',
  'bud': 'Budapest',
  'tri': 'Trieste',
  'ven': 'Venice',
  'pie': 'Piedmont',
  'ruh': 'Ruhr',
  'tyr': 'Tyrolia',
  'kie': 'Kiel',
  'n/swi': 'Switzerland',
  'n/ire': 'Ireland',
  'n/cor': 'Corsica',
  'n/sar': 'Sardinia',
  'n/mal': 'Mallorca',
  'n/sic': 'Sicily',
  'n/cre': 'Crete',
}